name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Test-self-hosted:
    runs-on: self-hosted

    steps:
      - name: Checkout- Code
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          hostname
          whoami
          kubectl version --client
          docker --version
