name: Self Hosted Runner Workflow

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Test
        run: |
          echo "Hello from self-hosted runner"
          hostname
